### PR TITLE
Add unstable for win_psrepository_info

### PR DESCRIPTION
**Pull request by briantist**
##### SUMMARY

Issue described in #83 

Similar to PR #82 but for `win_psrepository_info`.

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jborean93** [comment]
Sigh I thought I did this with https://github.com/ansible-collections/community.windows/pull/82 but I put it in the wrong target. Are you able to remove `unstable` from `win_psrepository` in this PR?

**Comment by briantist** [comment]
yeah no problem, one minute

**Comment by briantist** [comment]
hey I noticed something making this change. In `win_psrepository_info` I didn't use `setup_remote_tmp_dir`, whereas I did in `win_psrepository`.

It didn't seem to cause any problems initially. Any reason why that might affect httptester?

**Comment by jborean93** [comment]
I don't think so as the error happening here is it failing to access the actual HTTP tester. When I was testing it the ports were definitely forwarded and the hosts entry was set up properly but something was stopping the host from accessing the httptester site. I could never narrow it down as it ran fine by itself and sometimes worked with others.

Ultimately I just didn't have time to investigate it further so decided to mark it as unstable (although I failed at that).

**Comment by briantist** [comment]
The module names and test structures are so similar, easy mistake to make 😅

**Comment by jborean93** [comment]
I don't think it's a problem with the group it is in, we can even see that in this CI run it ran perfectly fine. There's some sort of problem with some of the other tests that are running or maybe just when it runs in the group that's a problem. Setting it to unstable will just allow the nightly CI to be green but if someone makes a change to the module it will still run in CI.

**Pull request merged**
