### PR TITLE
Add `accept_license` option to `win_psmodule`

### LINKED ISSUE #340: win_psmodule needs to address -AcceptLicense parameter
##### SUMMARY

Support the AcceptLicense parameter for the Install-Module powershell cmdlet used by win_psmodule's Install-PsModule function.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_psmodule -> Function Install-PsModule

##### ADDITIONAL INFORMATION

There are some PowerShell modules that require the -AcceptLicense parameter to be passed to Install/Update-Module. For example, the HPCMSL module has a dependent module HP.Private that will not install without passing this parameter and returns an error.

This could be handled by adding an optional parameter to the win_psmodule, or by automatically applying it in the Install-PsModule function. I think best practice should be to add it as a boolean option to win_psmodule and default to false. This would be consistent retroactively with existing playbooks, and would help document when the parameter is required.

```yaml
- community.windows.win_psmodule:
    name: HPCMSL
    state: latest
    acceptlicense: true
```

### PR DESCRIPTION
**Pull request by briantist**
##### SUMMARY

Fixes #340 

Adds `accept_license` option to `win_psmodule` so that modules requiring license acceptance can be installed.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

win_psmodule

##### ADDITIONAL INFORMATION

N/A

### CODE REVIEW

**Comment by briantist** [comment]
It turns out the way to use PowerShellGet Format 2.0 is to add a _tag_ with the value of `PowerShellGetFormatVersion_2.0` to module 😖 ...cool.

**Comment by briantist** [comment]
The remaining failures are all galaxy 429 errors. 
The last commit https://github.com/ansible-collections/community.windows/pull/411/commits/3e79a3c7b8cbeb4b5e6e650b6f66fe50b32a8cc7 only adds a single to a docs description.

The checks on the previous commit https://github.com/ansible-collections/community.windows/pull/411/commits/8db300665dc9efa5642eb0b0ad2f0eafe63864f2 all completed successfully.

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Looks like `-AcceptLicense` and other license functionality was added in [PowerShellGet 1.5.0](https://github.com/PowerShell/PowerShellGetv2/blob/master/CHANGELOG.md#1500) which is below our minimum requirements of 1.6.0. The changes here should be fine as long as someone follows our requirements note.

**Comment by Iwifia** [comment]
I am not sure that this is working as expected. 

`"msg": "Problems installing PowerShellGet module: A parameter cannot be found that matches parameter name 'AcceptLicense'.",`

is what I am receiving while using

```
    - name: Install PowerShellGet
      community.windows.win_psmodule:
        name: PowerShellGet
        accept_license: yes
        state: latest
```

**Comment by briantist** [comment]
@Iwifia the change has not been released yet as far as I know, you could work around it now with an earlier version of the collection, or by installing from git. This may help:
- https://github.com/ansible-collections/community.windows/issues/424#issuecomment-1233066558

**Pull request merged**
