### PR TITLE
AZP: update default container version

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-807391460

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
ERROR: 500: error: instance token not unique

**Comment by Andersson007** [comment]
```
13:30 TASK [win_hotfix : assert install hotfix check] ********************************
13:30 task path: /root/ansible_collections/community/windows/tests/output/.tmp/integration/win_hotfix-40aumte7-ÅÑŚÌβŁÈ/tests/integration/targets/win_hotfix/tasks/tests_2012R2.yml:69
13:31 fatal: [windows-2012-R2]: FAILED! => {
13:31     "assertion": "install_hotfix_check is changed",
13:31     "changed": false,
13:31     "evaluated_to": false,
13:31     "msg": "Assertion failed"
13:31 }
```

**Comment by Andersson007** [comment]
cc @jborean93 @briantist

**Review by jborean93 — APPROVED** [review]

**Comment by Andersson007** [comment]
@jborean93 thanks for reviewing and merging!

**Pull request merged**
