### PR TITLE
win_psrepository - add script and publish options, resolve locations

### PR DESCRIPTION
**Pull request by jborean93**
_From @briantist on Feb 17, 2020 21:17_

##### SUMMARY

* Add parameters for script and publish locations ( Fixes #67501 )

* Allow for forced update
  * Normal mode of operation on existing repositories is to update only the settings you supplied (same as previously)
  * `force` will make the repository match your settings exactly, by unregistering and re-registering the repository if there are changes
  * some desired changes can't be made without `force`, like if you wanted to "unset" a publish location after having previously set it to any value; there's no way to do that without registering anew.
* Add new tests for above.

Fixes: https://github.com/ansible-collections/community.windows/issues/48

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

 lib/ansible/modules/windows/win_psrepository.ps1

##### RELATED PRs:
- #67674 
- #67594 

_Copied from original issue: ansible/ansible#67499_

### CODE REVIEW

**Comment by jborean93** [comment]
_From @briantist on Feb 29, 2020 18:56_

ready_for_review

**Comment by briantist** [comment]
@jborean93 this is missing most of the latest changes to the original PR, I'm guessing just a timing issue with when those changes were made vs the copy that was used for migration.

How can I bring this up-to-date? Totally fine creating a new PR but I also don't know how to set up my local environment to do development anymore, with the split. How should I proceed?

**Comment by jborean93** [comment]
Must have just missed the changes sorry. Typically maintainers of a repo can commit and push to another PR but in this case I don't think you are a maintainer yet. What I recommend if you migrate your existing PR yourself to continue working on it just like ansible/ansible. What you need to do is

* Fork this repo
* Either manually recreate the PR, or
* Use the migration script I've written to do that for you https://gist.github.com/jborean93/1a060f4c7c17bbecd94cc1597e580b54

The migration script requires a valid fork to be created an a personal access token in GitHub which instructions on how to create that at https://gist.github.com/jborean93/1a060f4c7c17bbecd94cc1597e580b54#file-ansible_migrate-py-L97. In this case you would run

```
./ansible_migrate.py -p 67499 -c community.windows -r git@github.com:briantist/community.windows.git --token gh_token
```

The `-p` argument is the PR number on ansible/ansible to get the changes from, `-c` is the target collection name under the [ansible-collections](https://github.com/ansible-collections) or, `-r` is the git URL for the fork to migrate the PR changes to and `--token` is the GitHub personal access token to use for write access.

Once you have done that I can close this PR and we can continue the review process there.

**Comment by briantist** [comment]
Thanks @jborean93 . I tried the migrator, but the results were actually the same as this one. It seems there was some kind of conflict so the rebase never finished, which explains the missing stuff. The error if you're interested:
```
Applying: Update win_psrepository documentation
.git/rebase-apply/patch:109: trailing whitespace.
- name: Add an untrusted repository 
.git/rebase-apply/patch:135: trailing whitespace.
    
error: patch failed: plugins/modules/win_psrepository.py:62
error: plugins/modules/win_psrepository.py: patch does not apply
Patch failed at 0005 Update win_psrepository documentation
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Pushing branch to remote
```

In any case I'm not worried about it, I made a new branch on my new fork and made a PR manually. There weren't a lot of non-code review comments to bring over anyway.

### New PR: #56 

This one can be closed out.

**Comment by jborean93** [comment]
Thanks @briantist

**Pull request closed without merging**
