### PR TITLE
Tests: add testing against 2.11

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

The PR was made with a script, please recheck before merge

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
Not sure the errors are related

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Seems like the tests are already broken and needs to be fixed up. I don't see it being related to this PR so going to merge it in.

**Comment by jborean93** [comment]
Ahh looking at the error it's related to a problem in `win_template` with the latest devel code. This has been fixed in `ansible.windows` but a release hasn't occurred yet so `c.w` is still using the broken version https://github.com/ansible-collections/ansible.windows/pull/200.

**Comment by Andersson007** [comment]
@jborean93 thanks!

**Pull request merged**
