### PR TITLE
[DO NOT MERGE] test pr for #353

### PR DESCRIPTION
**Pull request by briantist**
##### SUMMARY

testing #353 with an incorrect change to documentation

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

laps

### CODE REVIEW

**Comment by jborean93** [comment]
Too quick for me, was just about to submit a PR :) The comment looks great and definitely better than before.

**Comment by briantist** [comment]
@jborean93 perhaps the message could use some emojis or other attention grabbing 🛑⚠❌🚫

**Comment by jborean93** [comment]
Personally I find them distracting but don't really mind either way. If anything it would be cool to substitute the `.py file(s)` with the actual link to the `.py` file but that's really just wishful thinking for the future.

**Comment by briantist** [comment]
> Personally I find them distracting but don't really mind either way. If anything it would be cool to substitute the `.py file(s)` with the actual link to the `.py` file but that's really just wishful thinking for the future.

sgtm, I won't add any emojis then :)

The link would be nice, I'm not sure how easy it would be to generate the link accurately just from knowing the RST, like if there were a module and a plugin that shared the same name, or things like that. Probably doable, but will have to be a later contribution.

**Pull request closed without merging**
