### PR TITLE
New Module: win_dhcp_lease

### PR DESCRIPTION
**Pull request by jborean93**
_From @joezollo on Oct 01, 2019 14:07_

##### SUMMARY
The win_dhcp_lease module manages Windows Server DHCP Leases/Reservations.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
win_dhcp_lease

##### ADDITIONAL INFORMATION
Includes Integration Tests - See documentation file for full details on how the module works.

_Copied from original issue: ansible/ansible#63009_

### CODE REVIEW

**Comment by jborean93** [comment]
_From @DouglasHeriot on Oct 03, 2019 02:34_

This is exactly what I need!
Would it make sense to rename this module to `windows_dhcp_lease`, and then in future create another module `windows_dhcp_scope` for managing scopes? The name `windows_dhcp` seems a bit broad.

**Comment by jborean93** [comment]
_From @joezollo on Oct 03, 2019 13:07_

Thanks @DouglasHeriot ! I am working on win_dhcp_scope actually.

I agree with your suggestion, win_dhcp_lease makes more sense, i'm working on a refactor! Should I close this PR out and re-submit or just continue committing?

**Comment by jborean93** [comment]
_From @ShachafGoldstein on Oct 04, 2019 17:09_

Up to you basically

**Comment by jborean93** [comment]
_From @joezollo on Oct 31, 2019 09:22_

Hi all, happy to discuss this PR - I welcome positive and critical feedback!

**Comment by jborean93** [comment]
_From @jborean93 on Dec 04, 2019 08:28_

Thinking about this further I think this module is probably better suited towards an Ansible collection and not part of Ansible itself. It would fit in well with a collection that is based on other DHCP modules that manage a DHCP server.

I don't want to take away from the work you've done so far. The testing and module setup you have done so far is excellent but modules to manage external services is not really something we are looking at adding to the main Ansible distribution right now.

cc @nitzmahone what are your thoughts on this?

**Comment by jborean93** [comment]
_From @joezollo on Dec 04, 2019 15:46_

Thank you for the excellent feedback @jborean93 !

I'm happy to make the requested changes and I agree with all your points.

In terms of whether or not this module belongs in the Ansible distribution - I think it does since it deals with an essential Windows Server service. For example, Ansible currently has modules for other essential Windows Server services like Active Directory and DNS (managing AD users / DNS records). 

Either way, i'm committed to making this module available to users one way or another!

**Comment by joezollo** [comment]
Hey @jborean93 - I saw that this was migrated, i'd love to get this properly committed into the collection. I have the changes that you recommended as well as fixes for the CI but i'm not sure what branch I should commit to.

**Comment by jborean93** [comment]
@joezollo you may need to just create a new PR as I don't think you can make changes to this branch without being a contributor first :( Basically you should create a fork of this repo and just commit your changes onto that.

The main things to note that need to change or aren't needed anymore

* You can remove the `version_added` entries in the docs. This is a brand new collection with no release yet
* You no longer need to skip the 2008/R2 hosts in the aliases file, we don't test them in CI anymore
* Any references to a module/action plugin that was core need to be done with the fully qualified collection name, i.e. `win_reboot` becomes `ansible.windows.win_reboot` and so on. Looking at your task you need to do this for every `win_feature`, `win_shell`, and `win_reboot` task you have

Apart from that things look good and I'm looking forward to seeing this being added to the collection. Once you do open a new PR I'll close this one.

**Comment by joezollo** [comment]
@jborean93 - Once again, thank you for the excellent feedback! I'll get started on this 👍

**Comment by joezollo** [comment]
@jborean93 Thank You - we can go ahead and close this PR, it has been supersceded by https://github.com/ansible-collections/community.windows/pull/75

**Comment by jborean93** [comment]
Thanks, will have a look at #75 sometime this week.

**Pull request closed without merging**
