### PR TITLE
adding support for txt in win_dns_record

### PR DESCRIPTION
**Pull request by sgruber94**
##### SUMMARY

Adding support for TXT Records

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
win_dns_record

##### ADDITIONAL INFORMATION

```
- name: Creating a TXT record with descriptive Text
  community.windows.win_dns_record:
    name: "test"
    state: present
    type: "TXT"
    value: "justavalue"
    zone: "example.com"

```

### CODE REVIEW

**Review by jborean93 — CHANGES_REQUESTED** [review]
Unfortunately there are a lot of formatting changes to this module which are unrelated to the functionality that is actually being added. I cannot do a proper review or merge in these changes as they are. Please keep the style and formatting the way the module was beforehand and just add in the functionality you are trying to add.

Some things I noticed just from a brief glance

* This will require a changelog fragment to help build the changelog when we release the next collection version
* It requires tests for the new functionality, feel free to have a look at the existing ones https://github.com/ansible-collections/community.windows/tree/main/tests/integration/targets/win_dns_record/tasks when adding TXT tests
* Documentation should document what collection version the `TXT` type was added, look at the existing entries for things like `NS`, `SRV` to see how they did it.

**Comment by billabongrob** [comment]
@sgruber94 Any updates on this one?

**Comment by sgruber94** [comment]
@billabongrob I will update it next week.

**Comment by jborean93** [comment]
Before I can review it you will need to rebase the PR, it includes commits that are already in the main branch and has a merge conflict.

**Comment by sgruber94** [comment]
I will do

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
