### PR TITLE
Initial winget module

### LINKED ISSUE #89: Ansible module to support the Windows package manager (winget)
##### SUMMARY
I think that Ansible should support the Windows package manager, [announced at Build 2020](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_winget

##### ADDITIONAL INFORMATION
```yaml
- name: Install PowerToys
  win_winget:
    name: Microsoft.PowerToys
```
References:
- https://docs.microsoft.com/en-gb/windows/package-manager/
- https://github.com/microsoft/winget-pkgs
- https://github.com/microsoft/winget-cli

### PR DESCRIPTION
**Pull request by JamieMagee**
##### SUMMARY
Initial implementation of `win_winget` module. Closes #89.

This module should, probably, not be merged until `winget` hits v1.0, as it's currently missing core functionality. However, I plan to work on this as features are added to `winget`.

See [Windows Package Manager v1.0 Roadmap](https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md) for more details.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
win_winget

##### ADDITIONAL INFORMATION
References:
- https://docs.microsoft.com/en-gb/windows/package-manager/
- https://github.com/microsoft/winget-pkgs
- https://github.com/microsoft/winget-cli

Reopening this PR so it doesn't get lost in the master -> main migration

### CODE REVIEW

**Comment by fam4r** [comment]
The Winget 1.0 version has been released

https://github.com/microsoft/winget-cli/releases/tag/v1.0.11451

**Comment by kradalby** [comment]
Any update on this? Would love to see that up and running

**Comment by JamieMagee** [comment]
I don't have capacity to pick this up right now. Feel free to add your work on top of my existing branch.

**Comment by jborean93** [comment]
Closing due to the age of the PR. If someone wishes to continue with the work they can submit a new PR with the changes requested added in.

Also a side note, I've not actually tried this or looked into it further but I've seen reports that winget may not work under WinRM https://github.com/microsoft/winget-cli/issues/256. This might mean that any proposed modules need to be run with `become` which is not ideal at all.

**Pull request closed without merging**
