### PR TITLE
Update win_domain_user Module to Support SPN's & Kerberos Delegates

### PR DESCRIPTION
**Pull request by zollo**
##### SUMMARY
Updates the `win_domain_user` module to add support for SPN's (`ServicePrincipalNames`) and Kerberos Delegates (`PrinicpalsAllowedToDelegate`).

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
win_domain_user

##### ADDITIONAL INFORMATION
* Module refactored to use the new CSharp interface
* Includes updated integration tests

### CODE REVIEW

**Comment by zollo** [comment]
It looks like CI is failing because of issues unrelated to my code.

**Comment by zollo** [comment]
recheck

**Comment by jborean93** [comment]
> It looks like CI is failing because of issues unrelated to my code.

The sanity has just been fixed but looks like Galaxy is having some problems that will hopefully get resolved soon.

**Comment by jborean93** [comment]
At a glance the changes look good, will need a changelog fragment to document the changes that have been added. Just for my understanding you are using this to create a domain account for use by a service with it's own SPN's and principals it can delegate to? I'll try to test out the changes either this week or next week.

**Comment by zollo** [comment]
> At a glance the changes look good, will need a changelog fragment to document the changes that have been added. Just for my understanding you are using this to create a domain account for use by a service with it's own SPN's and principals it can delegate to? I'll try to test out the changes either this week or next week.

I'll get that fragment added ASAP! The use case you mentioned is fairly common and the modifications to this module would make that possible. Example: IIS AppPool Service Acct. -> MSSQL Service Acct.

**Review by jborean93 — APPROVED** [review]
Thanks for the PR, I've had to make some minor changes to get the tests running but everything else looks great.

**Pull request merged**
